//! Phase 3 — Media: Image upload (inspected via `media::inspect`),
//! microphone/camera live streaming (`StreamInfo` stats), and transport events (play/pause/stop).
//!
//! Run: `cargo run -p grio --example media`

fn main() -> grio::Result<()> {
    use grio::*;

    App::new("Media Showcase · grio")

        // Analyze image + camera stats (both "Analyze" button and Run button
        // generated by `on_submit` share the same handler).
        .on_click("analyze", analyze)
        .on_submit(analyze)

        // On every live audio chunk: read server-side stats + update output.
        .on_stream("mic_in", |ctx| {
            if let Ok(s) = ctx.get::<StreamInfo>("mic_in") {
                ctx.set("stats_out", format!("mic: {} · {} · {} chunks", s.mime, s.kb(), s.chunks));
                if s.chunks % 5 == 0 {
                    ctx.alert(AlertLevel::Info, format!("live mic: {} ({})", s.kb(), s.mime));
                }
            }
            Ok(())
        })
        .flow(&["mic_in"], &["stats_out"])

        .on_play("cam_view", |ctx| {
            ctx.alert(AlertLevel::Info, "playback started (play)");
            Ok(())
        })
        .on_pause("cam_view", |_| Ok(()))
        .on_stop("cam_view", |ctx| {
            ctx.alert(AlertLevel::Warn, "stream stopped (stop)");
            Ok(())
        })

        .subtitle("Image / Audio / Video components: upload, live streaming, and transport events.")
        .item(Markdown::new("intro").text(
            "# Media\n\nUpload an **image** (server inspects type, bytes and dimensions), test **live microphone** or **live camera**, and observe stream metrics alongside `play` / `pause` / `stop` events.",
        ))
        .row(|r| {
            r.item(Image::new("img_in").label("Image (upload)").interactive(true));
            r.item(Output::new("facts_out").label("Server Inspection"));
        })
        .row(|r| {
            r.item(Audio::new("mic_in").label("Live Mic").interactive(true).live(true));
            r.item(Video::new("cam_in").label("Live Camera").output().live(true));
        })
        .row(|r| {
            r.item(Output::new("stats_out").label("Mic Streaming Stats"));
            r.item(Output::new("cam_stats").label("Camera Stats"));
        })
        .item(Video::new("cam_view").label("Video Player (play / pause / stop)"))
        .item(Button::new("analyze").label("Analyze"))
        .panel("How it works", |p| {
            p.item(Markdown::new("how").text(
                "- **image**: Data URL sent on `change`; server reads via `ctx.get_str` and inspects (MIME, bytes, PNG/GIF/JPEG dimensions).\n- **mic / camera**: `MediaRecorder` streams chunks over WebSocket `{ t:stream }`; server tracks `StreamInfo { mime, bytes, chunks }`, available via `ctx.get::<StreamInfo>`.\n- **player**: **play / pause / stop** transport buttons emit media events → `App::on_play` / `on_pause` / `on_stop`.",
            ));
        })
        .launch("127.0.0.1:7860")
}

fn analyze(ctx: &mut grio::Context) -> grio::Result<()> {
    use grio::*;

    if let Some(data_url) = ctx.get_str("img_in") {
        if let Some(info) = media::inspect(data_url) {
            let s = format!(
                "✓ Image Inspection\n  Type: {}\n  Size: {} bytes\n  Dimensions: {} × {} px\n  Summary: {}",
                info.mime,
                info.size_bytes,
                info.width.map_or("-".to_string(), |w| w.to_string()),
                info.height.map_or("-".to_string(), |h| h.to_string()),
                info.description(),
            );
            ctx.set("facts_out", s);
            ctx.alert(
                AlertLevel::Success,
                format!("Image analyzed: {} bytes", info.size_bytes),
            );
        } else {
            ctx.set("facts_out", "inspection error: unrecognized image format");
            ctx.alert(AlertLevel::Error, "failed to parse image format");
        }
    } else {
        ctx.set("facts_out", "(no image provided)");
        ctx.alert(AlertLevel::Warn, "please upload an image first");
    }

    if let Ok(s) = ctx.get::<StreamInfo>("cam_in") {
        ctx.set(
            "cam_stats",
            format!("camera: {} · {} · {} chunks", s.mime, s.kb(), s.chunks),
        );
    }
    Ok(())
}
