[package]
name = "grio-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "../../README.md"
description = "CLI tool and showcase runner for grio applications"

[[bin]]
name = "grio"
path = "src/main.rs"

[dependencies]
grio = { path = "../grio", version = "0.1.0" }
